### ISSUE TITLE
mailnag doesn't work with debian sretch

### ISSUE THREAD

**Issue by Cherkah** [pulb/mailnag#119]
1)mailnag icon do not appear on the topbar

2) i can not set up a email adress by dialog:
``AttributeError:` Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))`

3) when i close the mailnag-config window i got in the terminal:
`/usr/lib/python2.7/dist-packages/Mailnag/common/credentialstore.py:38: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
Traceback (most recent call last):
  File "/usr/bin/mailnag", line 40, in <module>
    from Mailnag.daemon.mailnagdaemon import MailnagDaemon
  File "/usr/lib/python2.7/dist-packages/Mailnag/daemon/mailnagdaemon.py", line 32, in <module>
    from Mailnag.daemon.idlers import IdlerRunner
  File "/usr/lib/python2.7/dist-packages/Mailnag/daemon/idlers.py", line 28, in <module>
    from Mailnag.common.imaplib2 import AUTH
ImportError: No module named imaplib2`

4) that is what i get in the terminal:
`~$ mailnag-config
/usr/local/bin/mailnag-config:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/lib/python2.7/dist-packages/Mailnag/common/credentialstore.py:38: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
/usr/lib/python2.7/dist-packages/Mailnag/plugins/goaplugin.py:24: PyGIWarning: Goa was imported without specifying a version first. Use gi.require_version('Goa', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Goa
/usr/lib/python2.7/dist-packages/Mailnag/plugins/soundplugin.py:26: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
/usr/lib/python2.7/dist-packages/Mailnag/plugins/libnotifyplugin.py:27: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify, Gio, Gtk
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 326, in _on_btn_add_account_clicked
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler expander_folders_activate not found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 340, in _on_btn_edit_account_clicked
    self._edit_account()
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/configwindow.py", line 242, in _edit_account
    d = AccountDialog(self._window, acc)
  File "/usr/lib/python2.7/dist-packages/Mailnag/configuration/accountdialog.py", line 76, in __init__
    self._entry_account_folder.set_placeholder_text(_("optional"))
AttributeError: 'NoneType' object has no attribute 'set_placeholder_text'
Launching Mailnag daemon.

`
so does mailnag works with debian 4.4 testing?

**Comment by pulb** [comment]
Which mailnag version are you using? Which extension version? Did you install a package or did you install from source?

If you're running Mailnag 1.2 / mailnag-gnome-shell 3.18 I'm afraid there's currently nothing I can do since testing may come with newer/incompatible versions of dependencies like GTK.

**Comment by Cherkah** [comment]
thank for your reply. 
 
this bug was present on jessie.
sometimes i have the icons on the top bar and sometimes not. when the icon appears it give me the setup things but do not show me my mails and the counter numbers.

package mailnag version: 1.1.0-1
package gnome-shell-mailnag: 3.16.0-1
source mailnag goa: 1.2

**Comment by pulb** [comment]
I'm confused - do you get those errors in jessie or in stretch?

**Comment by Cherkah** [comment]
i'm on stretch (testing).

**Comment by pulb** [comment]
Ok, but gnome-shell-mailnag 3.16 can't show an indicator without mails and counter. This feature was introduced in mailnag-gnome-shell 3.18.

**Comment by Cherkah** [comment]
ok pulb, i passed through the errors by dl the mailnag-gnome-shell 3.18 (github one) and rm the package one. them, i sat up the package unless goa-plugin keyring. and now all do well!
i get the icons and counters and all stuff.
thank.

**Comment by pulb** [comment]
Glad to see you got it working :smile:
